; Script generated by the Gemini CLI for fsQCA_pro
; To compile: Use Inno Setup Compiler (ISCC.exe)

#ifndef AppVersion
  #define AppVersion "1.0.0"
#endif

[Setup]
AppId={{D3C6E5B4-A8F1-4F9A-A3D5-7C2B7E1B5A9F}
AppName=fsQCA_pro
#ifndef AppVersion
  #define AppVersion "0.7.5"
#endif
AppVersion={#AppVersion}
AppPublisher=ghanekark
AppPublisherURL=https://github.com/ghanekark/fsqca_pro
AppSupportURL=https://github.com/ghanekark/fsqca_pro/issues
AppUpdatesURL=https://github.com/ghanekark/fsqca_pro/releases
DefaultDirName={autopf}\fsQCA_pro
DisableProgramGroupPage=yes
UninstallDisplayName=fsQCA_pro
CloseApplications=no
RestartApplications=no

; Modern UI 2.0
WizardStyle=modern
SetupIconFile=installer_icon.ico

; Output and Compression
OutputBaseFilename=fsQCA_pro_setup
OutputDir=..\Output
Compression=lzma2/max
SolidCompression=yes

; Privileges and Architecture
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

; Version Info for Windows Explorer
VersionInfoCompany=ghanekark
VersionInfoDescription=fsQCA_pro Installer
VersionInfoCopyright=Copyright (C) 2026 ghanekark

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "..\dist\fsQCA_pro.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "installer_icon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Start Menu Shortcut (Always created)
Name: "{autoprograms}\fsQCA_pro"; Filename: "{app}\fsQCA_pro.exe"; IconFilename: "{app}\installer_icon.ico"
; Desktop Shortcut (Optional task)
Name: "{autodesktop}\fsQCA_pro"; Filename: "{app}\fsQCA_pro.exe"; IconFilename: "{app}\installer_icon.ico"; Tasks: desktopicon

[Run]
; Option to launch the app immediately after installation
Filename: "{app}\fsQCA_pro.exe"; Description: "{cm:LaunchProgram,fsQCA_pro}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
